payment-backend/payments/payments/urls.py
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularRedocView, SpectacularSwaggerView

from payment_api.routers import router

from payment_api import views

from payment_api.views import ClientsViewSet, PaymentCompleteAPIView, SendPostRequestViewSet

from rest_framework.routers import DefaultRouter


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Swagger UI:
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    # Redoc UI:
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('checkout/<uuid:pk>/', views.payment_pid, name='payment_pid'),
    path('payment/<uuid:cid>/<uuid:pid>/', views.payment, name='payment'),
    # path('process_payment/<str:client_secret>/', views.process_payment, name='process_payment'),

    # URL pattern for the form
    path('registration/', ClientsViewSet.as_view({'post': 'create', 'get': 'list'}), name='registration'),
    path('send_post_request/', SendPostRequestViewSet.as_view({'post': 'create', 'get': 'list'}), name='send_post_request'),
    # path('send-post-request/', views.SendPostRequestView.as_view(), name='send_post_request'),

    path('payment_complete/', PaymentCompleteAPIView.as_view(), name='payment_complete'),
]

payment-backend/payments/payment_api/models.py
from django.db import models
import uuid

# Create your models here.

class Payments(models.Model):
    class Status(models.IntegerChoices):
        ACTIVE = 1, 'Active'
        INACTIVE = 2, 'Inactive'

    class Type(models.TextChoices):
        CREDITCARD = 'CC', 'Credit Card'
        PAYPAL = 'P', 'Paypal'
        OTHER = 'O', 'Others'

    id = models.UUIDField(
        primary_key = True, 
        default = uuid.uuid4,
        editable = True,
        unique=True
        )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=100)
    paid = models.BooleanField(default=False)
    name = models.CharField(max_length=120)
    # payment_unique_key = models.CharField(max_length=36, blank=False)    
    client_unique_key = models.UUIDField(
        primary_key = False, 
        default = uuid.uuid4,
        editable = True,
        unique=False,
        blank=False,
        )
    is_active = models.BooleanField(default=True)
    status = models.IntegerField(choices=Status.choices, default=Status.ACTIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Clients(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=254, unique=True)
    paypal_client_id = models.CharField(max_length=80)
    PLAN_CHOICES = (
        ('a', 'Standard'),
        ('b', 'Premium'),
        ('c', 'Premium Plus')
    )
    membership_plan = models.CharField(max_length=1, choices=PLAN_CHOICES)
    unique_key = models.UUIDField(
        primary_key = False,
        default = uuid.uuid4,
        editable = True,
        unique=True
        )
    STATE_CHOICES = (
        ('a', 'Active'),
        ('i', 'Inactive'),
        ('s', 'Suspended'),
        ('w', 'Awaiting Approval')
    )
    state = models.CharField(max_length=1, choices=STATE_CHOICES, default='w')
    
    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = "API Clients"

payment-backend/payments/payment_api/forms.py
# forms.py
from django import forms
from .models import Payments, Clients
from django.core.exceptions import ValidationError

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payments
        fields = ('amount', 'description',)
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ClientsForm(forms.ModelForm):
    #email = forms.EmailField(required=True, error_messages={'invalid': 'Your email address is incorrect'})
    #state = forms.CharField(widget=forms.HiddenInput(), initial='w')
    #name = forms.CharField(required=True, max_length=300)
    #membership_plan = forms.CharField()
    class Meta:
        model = Clients
        fields = ['name', 'email', 'iban', 'membership_plan']  # Specify fields to include in the form

    def clean_email(self):
        email = self.cleaned_data['email']
        if Clients.objects.filter(email=email).exists():
            # Email is valid, perform your desired actions
            raise ValidationError("e-mail already exists")            
        return email
        
def form_validation_error(form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field, 'label') else 'Error', error)
    return msg

payment-backend/payments/payment_api/views.py
from django.shortcuts import render, redirect
# from django.http import JsonResponse
from rest_framework import viewsets, status
from rest_framework.response import Response
from drf_spectacular.utils import extend_schema
from rest_framework.views import APIView
from rest_framework.exceptions import MethodNotAllowed
from django.http import JsonResponse
from django.views import View
from .serializers import PaymentsSerializer, PaymentsPostSerializer, PaymentsListSerializer, PaymentsCreateUpdateSerializer, PaymentCompleteSerializer, ClientsSerializer
import requests
#from django.views import View

from .models import Payments, Clients
#from .forms import PaymentForm

from .forms import ClientsForm, PaymentForm
import datetime
from django.contrib import messages
from django.urls import reverse




class PaymentsViewSet(viewsets.ModelViewSet):
    queryset = Payments.objects.all()

    def get_serializer_class(self):
        if self.action == 'list' or self.action == 'retrieve':
            return PaymentsListSerializer  # Serializer for GET requests
        elif self.action == 'create' or self.action == 'update' or self.action == 'partial_update':
            return PaymentsCreateUpdateSerializer  # Serializer for POST, PUT, PATCH requests
        else:
            return PaymentsSerializer  # Default serializer

def payment(request, cid, pid):
    print(request.headers)

    # Paypal
    clients = Clients.objects.get (unique_key=cid)
    payments = Payments.objects.get(id=pid)
    context = {'payments':payments, 'clients':clients}
    
    return render (request, 'payment.html', context)
    # End Paypal


def payment_pid(request, pk):
    print(request.headers)

    payments = Payments.objects.get(id=pk)
    context = {'payments':payments}
    
    return render (request, 'payment.html', context)

class PaymentCompleteAPIView(APIView):
    serializer_class = PaymentCompleteSerializer
    @extend_schema(
        description="Endpoint to complete payment by updating payment status",
        responses={200: None, 400: {"error": "Invalid JSON data"}}
    )
    
    def patch(self, request):
        # Assuming the request body contains JSON data
        try:
            body = self.request.data  # Access request data instead of request.body            

            # Query the database for the corresponding payment record
            payment = Payments.objects.get(id=body['paymentId'])

            # Update the 'paid' field of the payment record
            payment.paid = True
            payment.save()
            return Response({'message': 'Payment updated successfully'})
        except KeyError:
            return Response({'error': 'Invalid request data. Ensure paymentId is provided.'}, status=status.HTTP_400_BAD_REQUEST)
        except Payments.DoesNotExist:
            return Response({'error': 'Payment not found'}, status=status.HTTP_404_NOT_FOUND)

    def handle_exception(self, exc):
        if isinstance(exc, MethodNotAllowed):
            return Response({'error': 'Method not allowed'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)
        return super().handle_exception(exc)
    
    '''
    form = PaymentForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            payment = form.save(commit=False)
            payment.user = request.user
            payment.save()

            # Create a Stripe PaymentIntent
            stripe.api_key = settings.STRIPE_PRIVATE_KEY
            intent = stripe.PaymentIntent.create(
                amount=int(payment.amount * 100),
                currency='usd',
                metadata={'payment_id': payment.id}
            )

            # Redirect to the payment processing view
            return redirect('process_payment', intent.client_secret)

    context = {'form': form}
    return render(request, 'payment.html', context)
    '''

class ClientsViewSet(viewsets.ViewSet):
    queryset = Clients.objects.all()
    serializer_class = ClientsSerializer
    
    def create(self, request):
        form = ClientsForm(request.data)
        if form.is_valid():
            client = form.save()
            unique_key = client.unique_key 
            return render(request, 'success.html', {'unique_key': unique_key})
        else:
            return render(request, 'clients_form_retry.html', {'form': form})
        
    def retrieve(self, request):
        form = ClientsForm()
        return render(request, 'clients_form.html', {'form': form})
    
    def list(self, request):
        form = ClientsForm()
        return render(request, 'clients_form.html', {'form': form}) 
'''
class ClientsViewSet(viewsets.ViewSet):
    
    def create(self, request):
        # Perform any necessary validation on request.data if needed
        
        # Get or create Clients object
        client, created = Clients.objects.get_or_create()
        
        # Serialize the Clients object
        serializer = ClientsSerializer(client)
        
        # Render the clients_form.html template with the serialized data
        return render(request, 'clients_form.html', {'client_data': serializer.data})
    
    def list(self, request):
         # Render the clients_form.html template for GET requests
        return render(request, 'clients_form.html', {})
        '''


def process_payment(request, client_secret):
    if request.method == "POST":
        '''stripe.api_key = settings.STRIPE_PRIVATE_KEY
        intent = stripe.PaymentIntent.confirm(client_secret)'''

        if intent.status == 'succeeded':
            # Update the Payment model
            payment_id = intent.metadata['payment_id']
            payment = Payments.objects.get(id=payment_id)
            payment.paid = True
            payment.save()

            messages.success(request, 'Payment successful!')
            return redirect('success')

    context = {'client_secret': client_secret}
    return render(request, 'process_payment.html', context)

class SendPostRequestViewSet(viewsets.ViewSet):
    queryset = Payments.objects.all()
    serializer_class = PaymentsPostSerializer

    def list(self, request):
        return render(request, 'mb-way.html')

    def create(self, request):
        serializer = PaymentsPostSerializer(data=request.data)
        if serializer.is_valid():
            amount = serializer.validated_data['amount']
            description = serializer.validated_data['description']
            phone_value = serializer.validated_data['phone']

            current_datetime = datetime.datetime.now().isoformat()
            payload = {
            {    
                "merchant": {
                    "terminalId": 66779,
                    "channel": "web",
                    "merchantTransactionId": "teste 1"
                },
                "transaction": {
                    "transactionTimestamp": current_datetime,
                    "description": description,
                    "moto": False,
                    "paymentType": "PURS",
                    "amount": {
                        "value": amount,
                        "currency": "EUR"
                    },
                    "paymentMethod": [
                        "CARD",
                        "REFERENCE",
                        "QRCODE",
                        "MBWAY"
                    ]                        
                }                    
            }
            }
            url = "https://api.qly.sibspayments.com/sibs/spg/v2/payments"
            headers = {
                "X-IBM-Client-Id": "c59a9673-199a-4a6e-9767-4c6aa70fc910",
                "Content-Type": "application/json",
                "Authorization": "Bearer 0267adfae94c224be1b374be2ce7b298f0.eyJlIjoiMjAyODgxNjU2NDgxMSIsInJvbGVzIjoiTUFOQUdFUiIsInRva2VuQXBwRGF0YSI6IntcIm1jXCI6XCI1MDU0MjVcIixcInRjXCI6XCI2Njc3OVwifSIsImkiOiIxNzEzMjgzNzY0ODExIiwiaXMiOiJodHRwczovL3FseS5zaXRlMS5zc28uc3lzLnNpYnMucHQvYXV0aC9yZWFsbXMvREVWLlNCTy1JTlQuUE9SVDEiLCJ0eXAiOiJCZWFyZXIiLCJpZCI6Ijh6RWtRQUJaM2NlOTY3MzljMWIxNGU0NTBjYTNhMDVjMzBkNWJmM2QwYSJ9.51730f0d62b69c39b0a2bb5d4547f02e13e5110138946333323295414f94620368d060e4d6e90577d4cc555623bfefb3215655f5d8ad05c5bb0476f451a78cbe"
            }
            response = requests.post(url, headers=headers, json=payload)

            if response.status_code == 200:
                response_data = response.json()
                transaction_id = response_data.get("transactionId")
                status = response_data.get("status")
                transaction_signature = response_data.get("transactionSignature")

                phone_value = request.data.get('phone')

                if transaction_id and transaction_signature:
                    second_url = f"https://api.qly.sibspayments.com/sibs/spg/v2/payments/{transaction_id}/mbway-id/purchase"
                    second_headers = {
                        "Content-Type": "application/json",
                        "X-IBM-Client-Id": "c59a9673-199a-4a6e-9767-4c6aa70fc910",
                        "Authorization": f"Digest {transaction_signature}"
                    }
                    second_payload = {
                    {
                        "customerPhone": f"351#{phone_value}"
                    }
                    }
                    second_response = requests.post(second_url, headers=second_headers, json=second_payload)

                    if second_response.status_code == 200:
                        second_response_data = second_response.json()
                        purchase_status = second_response_data.get("status")
                        return JsonResponse({
                            'status': 'success',
                            'transactionId': transaction_id,
                            'paymentStatus': status,
                            'purchaseStatus': purchase_status
                        }, status=200)
                    else:
                        return JsonResponse({

payment-backend/payments/payment_api/templates/base.html
{% load static %}

<link rel="stylesheet" href="{% static 'payment_api/style.css' %}">

payment-backend/payments/payment_api/templates/clients_form.html
<!-- clients_form.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Registration</title>
	<meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


	<style type="text/css">
		body{
			background-color: #f0f0f0;			
		}
		h1{text-align: center;}
		h2{text-align: center;}
        form {
            text-align: leftt;
            margin: 0 auto; 
            width:600px;
        }
        input {
            width: 85%;
        }
        textarea {
            width: 95%;
        }
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px;
        }
        div.fixed {
            position: fixed;
            width: 600px;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
	</style>		

</head>
<body>
    <form method="post" action="{% url 'registration' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="fixed">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <h2 class="h5 mb-4">Client Registration</h2>
                <div class="row">
                    <div class="col-lg">                    
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" id="name" name="name">
                        </div>
                    </div>                           
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="form-group">
                            <label for="e-mail">E-mail:</label>
                            <input type="email" id="e-mail" name="email">
                        </div>
                    </div>                            
                </div>
                <div class="row">
                    <div class="col-lg">         
                        <div class="form-group">
                            <label for="iban">IBAN:</label>
                            <input type="text" id="iban" name="iban">
                        </div>
                    </div>                           
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="form-group">
                            <label for="membership_plan">Membership Plan:</label>
                            <select id="membership_plan" name="membership_plan">
                                <option value="a">Standard</option>
                                <option value="b">Premium</option>
                                <option value="c">Premium Plus</option>
                            </select>
                        </div>
                    </div>                            
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="center">                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>                
                </div>
            </div>
        </div>
    </form>
</body>
</html>

payment-backend/payments/payment_api/templates/clients_form_retry.html
<!-- clients_form_retry.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
    <meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <style type="text/css">
		body{
			background-color: #f0f0f0;			
		}
		h1{text-align: center;}
		h2{text-align: center;}
        form {
            text-align: leftt;
            margin: 0 auto; 
            width:600px;
        }
        input {
            width: 85%;
        }
        textarea {
            width: 95%;
        }
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px;
        }
        div.fixed {
            position: fixed;
            width: 600px;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
	</style>		

</head>
<body>
    <form method="post" action="{% url 'registration' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="fixed">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <h2 class="h5 mb-4">Client Registration</h2>
                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}: </strong>{{ error }}<br>
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-lg">                    
                        <div class="form-group">
                            <label for="id_name">Name:</label>
                            <input type="text" id="id_name" name="name" value="{{ form.data.name }}">
                        </div>
                    </div>                           
                </div>
                <div class="row">
                    <div class="col-lg">                        
                        <div class="form-group">
                            <label for="id_email">E-mail:</label>
                            <input type="email" id="id_email" name="email" value="{{ form.data.email }}">
                        </div>
                    </div>                            
                </div>
                <div class="row">
                    <div class="col-lg">         
                        <div class="form-group">
                            <label for="iban">IBAN:</label>
                            <input type="text" id="iban" name="iban">
                        </div>
                    </div>                           
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="form-group">
                            <label for="id_membership_plan">Membership Plan:</label>
                            <select id="id_membership_plan" name="membership_plan">
                                <option value="a">Standard</option>
                                <option value="b">Premium</option>
                                <option value="c">Premium Plus</option>
                            </select>
                        </div>
                    </div>                            
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="center">                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>                
                </div>
            </div>
        </div>
    </form>
</body>
</html>

payment-backend/payments/payment_api/templates/mb-way.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>MB-WAY Form</title>
  <style type="text/css">
    #root_phone { width: 250px; }
    h1{text-align: center;}      
  </style>		
</head>
<body>
  <div class="container">
    <div class="InstrumentForm__StyledInstrumentForm-sc-1gz9oaa-0 hOLkNQ">
      <div class="col-lg">
        <div class="card card-body">
        <div class="logo-container" align="center">
          <img class="logo-color" src="https://cdn.switchpayments.com/libs/dynamic-forms/img/payment-methods-logos/mbway-color.png" alt="MB WAY logo">
        </div>        
				<br>      
        <h1 id="amountDisplay"></h1>        
				<br>
      <div class="FormContainer__StyledFormContainer-g1spo-0 IFTXN" align="center">
        <form class="rjsf">
          <div class="form-helpers__StyledFieldsetWrapper-kwlz7r-0 iAbqid">
              <div class="FormFieldTemplate__StyledFormFieldTemplate-wtn2u3-0 ZceMM">
                <div class="input-label-container">
                  <label for="root_phone">Telefone</label>
                  <div class="input-container">
                    <input class="form-control" id="root_phone" label="Telefone" required="" placeholder="9XXXXXXXX" type="text">
                  </div>
                </div>
              </div>
              <!-- Hidden fields to pass amount and description -->
              <input type="hidden" id="amount">
              <input type="hidden" id="description">
          </div>
        </form>
      </div>      
			<br>
      <div class="ButtonsContainer__StyledButtonsContainer-sc-146l0pg-0 iWFvAL" align="center">
        <button class="Button__StyledButton-sc-1ptprjf-0 PrimaryButton__StyledPrimaryButton-sc-1bjfjfx-0 eZvWLg krvnFP" id="confirmButton">Confirmar</button>
      </div>
    </div>
    </div>
  </div>
  </div>
  <script>
    // Extract query parameters
    var urlParams = new URLSearchParams(window.location.search);
    var amount = urlParams.get('amount');
    var description = urlParams.get('description');

    // Display the amount
    document.getElementById('amountDisplay').textContent = amount + '€';
    // Set hidden fields
    document.getElementById('amount').value = amount;
    document.getElementById('description').value = description;

    document.getElementById('confirmButton').addEventListener('click', function(event) {
      event.preventDefault(); // Prevent the default form submission
    

      // Get the phone number from the input field
      var phoneValue = document.getElementById('root_phone').value;
      var amountValue = document.getElementById('amount').value;
      var descriptionValue = document.getElementById('description').value;
    
      // Make sure the phone number is not empty
      if (phoneValue.trim() === '') {
        alert('Please enter a valid phone number.');
        return;
      }
    
      // Make the AJAX request to submit the form data with the phone number
      var xhr = new XMLHttpRequest();
      var sendPostRequestUrl = "{{ send_post_request_url }}";
      xhr.open('POST', sendPostRequestUrl, false);
      xhr.setRequestHeader('Content-Type', 'application/json');
      xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    
      // Construct the JSON payload
      var payload = JSON.stringify({
        phone: phoneValue,
        amount: amountValue,
        description: descriptionValue
      });
    
      // Send the AJAX request
      xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          if (xhr.status === 200) {
            var response = JSON.parse(xhr.responseText);
            if (response.status === 'success') {
              // Handle success response
              alert('Payment successfully confirmed.');
            } else {
              // Handle error response
              alert('Failed to confirm payment. Please try again.');
            }
          } else {
            // Handle non-200 status code
            alert('Pedido de carregamento enviado, consulte a aplicação de MB Way no telemóvel. Tem 4 minutos para efetuar o pagamento.');
          }
        }
      };
      xhr.send(payload);
    });
    </script>
    

</body>
</html>

payment-backend/payments/payment_api/templates/mb-way1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MB WAY Payment</title>
</head>
<body>
    <form method="post" action="{% url 'mb-way-create' %}">
        {% csrf_token %}
        <label for="phone">Phone Number:</label>
        <input type="text" id="phone" name="phone" required>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

payment-backend/payments/payment_api/templates/payment_old.html
<!-- payment.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h2>Make a Payment</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Pay</button>
  </form>
{% endblock %}

payment-backend/payments/payment_api/templates/process_payment.html
<!-- process_payment.html -->
{% extends 'base.html' %}
{% block content %}
<h2>Processing Payment...</h2>
<p>Please wait while we process your payment.</p>
<!--
  {% load static %}
  <script src="https://js.stripe.com/v3/"></script>
  <script src="{% static 'js/payment.js' %}"></script>
  <script>
    processPayment('{{ client_secret }}');
  </script>
-->
{% endblock %}

payment-backend/payments/payment_api/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
		body{
			background-color: #f0f0f0;			
		}
		h1{text-align: center;}
		p{text-align: center;}
	</style>
</head>
<body>
    <h1>Your submission has been sent!</h1>
    <p>Your security key for payment processing is: {{ unique_key }}</p>
    <!-- Other success message or redirection content -->
</body>
</html>